### PR TITLE
decoders/mpg123: use `off_t` type for "offset" & "file_size"

### PR DESCRIPTION
**Pull request by Apaczer**
respectivly:
off_t sampleoff in mpg123_feedseek()
off_t size in mpg123_set_filesize()

I was getting a few errors when using `long` for LFS alias type, and matter becomes even more problematic with latest MPG123_API_VERSION and undefined ref. symbols output.

Was there a version when these were using `long` for data type?

### CODE REVIEW

**Comment by Apaczer** [comment]
From my understanting `long` is just a 32bit `off_t` mostly to be ok with Win32API (from [gnupng](https://www.gnupg.org/documentation/manuals/gpgme/Largefile-Support-_0028LFS_0029.html))

**Comment by Apaczer** [comment]
should resolve #4

**Comment by jhe2** [comment]
Thanks for your pull requests, I'll get to them soon.

**Comment by jhe2** [comment]
Merged!

**Pull request closed without merging**
